# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11task_status.proto\x12\x1e\x41rmoniK.api.grpc.v1.TaskStatus*\xc9\x02\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_STATUS_CREATING\x10\x01\x12\x19\n\x15TASK_STATUS_SUBMITTED\x10\x02\x12\x1a\n\x16TASK_STATUS_DISPATCHED\x10\x03\x12\x1a\n\x16TASK_STATUS_PROCESSING\x10\n\x12\x19\n\x15TASK_STATUS_PROCESSED\x10\x0b\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x04\x12\x15\n\x11TASK_STATUS_ERROR\x10\x05\x12\x16\n\x12TASK_STATUS_FAILED\x10\x06\x12\x17\n\x13TASK_STATUS_TIMEOUT\x10\x07\x12\x19\n\x15TASK_STATUS_CANCELING\x10\x08\x12\x18\n\x14TASK_STATUS_CANCELED\x10\tB\x16\xaa\x02\x13\x41rmoniK.Api.gRPC.V1b\x06proto3')

_TASKSTATUS = DESCRIPTOR.enum_types_by_name['TaskStatus']
TaskStatus = enum_type_wrapper.EnumTypeWrapper(_TASKSTATUS)
TASK_STATUS_UNSPECIFIED = 0
TASK_STATUS_CREATING = 1
TASK_STATUS_SUBMITTED = 2
TASK_STATUS_DISPATCHED = 3
TASK_STATUS_PROCESSING = 10
TASK_STATUS_PROCESSED = 11
TASK_STATUS_COMPLETED = 4
TASK_STATUS_ERROR = 5
TASK_STATUS_FAILED = 6
TASK_STATUS_TIMEOUT = 7
TASK_STATUS_CANCELING = 8
TASK_STATUS_CANCELED = 9


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023ArmoniK.Api.gRPC.V1'
  _TASKSTATUS._serialized_start=54
  _TASKSTATUS._serialized_end=383
# @@protoc_insertion_point(module_scope)
