// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto
#ifndef GRPC_worker_5fservice_2eproto__INCLUDED
#define GRPC_worker_5fservice_2eproto__INCLUDED

#include "worker_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ArmoniK {
namespace api {
namespace grpc {
namespace v1 {

class Worker final {
 public:
  static constexpr char const* service_full_name() {
    return "ArmoniK.api.grpc.v1.Worker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> Process(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(ProcessRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> AsyncProcess(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(AsyncProcessRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> PrepareAsyncProcess(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(PrepareAsyncProcessRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Process(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ArmoniK::api::grpc::v1::ProcessRequest,::ArmoniK::api::grpc::v1::ProcessReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* ProcessRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* AsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> Process(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(ProcessRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> AsyncProcess(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(AsyncProcessRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>> PrepareAsyncProcess(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>>(PrepareAsyncProcessRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Process(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ArmoniK::api::grpc::v1::ProcessRequest,::ArmoniK::api::grpc::v1::ProcessReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* ProcessRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* AsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Process_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Process(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Process() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Process<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Process() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Process(context); }));
    }
    ~WithCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ArmoniK::api::grpc::v1::ProcessRequest, ::ArmoniK::api::grpc::v1::ProcessReply>* Process(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Process<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Process() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Process() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Process() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Process(context); }));
    }
    ~WithRawCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ArmoniK::api::grpc::v1::ProcessReply, ::ArmoniK::api::grpc::v1::ProcessRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Process(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace v1
}  // namespace grpc
}  // namespace api
}  // namespace ArmoniK


#endif  // GRPC_worker_5fservice_2eproto__INCLUDED
